# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: webapp_test
          
      - image: circleci/redis

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Migrate database
          environment:
            PYTHONPATH: ./
          command: |
            . venv/bin/activate
            cd webapp
            flask db upgrade

      # - run:
      #     name: Run Webapp tests
      #     command: |
      #       . venv/bin/activate
      #       cd webapp
      #       python -m pytest
      
      - run:
          name: Run CDM tests
          command: |
            . venv/bin/activate
            cd credit_default_model
            python -m pytest

      - store_artifacts:
          path: test-reports
          destination: test-reports